-- MySQL Script generated by MySQL Workbench
-- Thu May 18 20:10:34 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema siga
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema siga
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `siga` DEFAULT CHARACTER SET utf8 ;
USE `siga` ;

-- -----------------------------------------------------
-- Table `siga`.`aviso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`aviso` (
  `idAviso` INT NOT NULL AUTO_INCREMENT,
  `nombreAviso` VARCHAR(45) NOT NULL COMMENT '	',
  `lugarAviso` VARCHAR(45) NOT NULL,
  `horaAviso` TIME NOT NULL,
  `fechaAviso` DATE NOT NULL,
  `descripcionAviso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAviso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(9) NOT NULL,
  `passwordUsuario` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`horarioAtencion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`horarioAtencion` (
  `idhorarioAtencion` INT NOT NULL AUTO_INCREMENT,
  `horaInicio` TIME NOT NULL,
  `horaFin` TIME NOT NULL,
  PRIMARY KEY (`idhorarioAtencion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`recepcionista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`recepcionista` (
  `idRecepcionista` INT NOT NULL AUTO_INCREMENT,
  `nombreRecepcionista` VARCHAR(45) NOT NULL,
  `telefonoRecepcionista` INT(15) NOT NULL,
  `correoERecepcionista` VARCHAR(45) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `horarioAtencion_idhorarioAtencion` INT NOT NULL,
  PRIMARY KEY (`idRecepcionista`),
  INDEX `fk_Recepcionista_usuario1_idx` (`usuario_idusuario` ASC),
  INDEX `fk_recepcionista_horarioAtencion1_idx` (`horarioAtencion_idhorarioAtencion` ASC),
  CONSTRAINT `fk_Recepcionista_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `siga`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recepcionista_horarioAtencion1`
    FOREIGN KEY (`horarioAtencion_idhorarioAtencion`)
    REFERENCES `siga`.`horarioAtencion` (`idhorarioAtencion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`historialObservaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`historialObservaciones` (
  `idHistorialObservaciones` INT NOT NULL AUTO_INCREMENT,
  `noObservacion` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idHistorialObservaciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`alumno` (
  `matriculaAlumno` VARCHAR(9) NOT NULL,
  `nombreAlumno` VARCHAR(45) NOT NULL,
  `apPaternoAlumno` VARCHAR(45) NOT NULL,
  `apMaternoAlumno` VARCHAR(45) NULL,
  `telefonoAlumno` INT(10) NOT NULL,
  `noInscripcionAlumno` INT(10) NOT NULL,
  `correoEAlumno` VARCHAR(45) NOT NULL,
  `semestreAlumno` INT(1) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`matriculaAlumno`),
  INDEX `fk_alumno_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_alumno_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `siga`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`seccion` (
  `idseccion` INT NOT NULL AUTO_INCREMENT,
  `noSeccion` INT(2) NOT NULL,
  PRIMARY KEY (`idseccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`asesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`asesor` (
  `noPersonalAsesor` INT NOT NULL AUTO_INCREMENT,
  `nombreAsesor` VARCHAR(45) NOT NULL,
  `apPaternoAsesor` VARCHAR(45) NOT NULL,
  `apMaternoAsesor` VARCHAR(45) NULL,
  `telefonoAsesor` INT(10) NOT NULL,
  `correoEAsesor` VARCHAR(45) NOT NULL,
  `horarioAtencion` VARCHAR(45) NOT NULL,
  `noGrupos` INT(2) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`noPersonalAsesor`),
  INDEX `fk_asesor_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_asesor_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `siga`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `creditosCurso` INT(5) NOT NULL,
  `codigoCurso` INT(20) NOT NULL,
  `nombreCurso` VARCHAR(45) NOT NULL,
  `noHorasTeoria` INT(5) NOT NULL,
  `noHorasPractica` INT(5) NOT NULL,
  `prerrequisitoCurso` VARCHAR(45) NOT NULL,
  `limiteAlumnosCurso` INT(5) NOT NULL,
  `moduloCurso` INT(5) NOT NULL,
  `nrcCurso` INT(10) NOT NULL,
  `periodoCurso` VARCHAR(45) NOT NULL,
  `fechaInicioCurso` VARCHAR(45) NOT NULL,
  `fechaFinCurso` VARCHAR(45) NOT NULL,
  `seccion_idseccion` INT NOT NULL,
  `asesor_noPersonalAsesor` INT NOT NULL,
  PRIMARY KEY (`idCurso`),
  INDEX `fk_curso_seccion1_idx` (`seccion_idseccion` ASC),
  INDEX `fk_curso_asesor1_idx` (`asesor_noPersonalAsesor` ASC),
  CONSTRAINT `fk_curso_seccion1`
    FOREIGN KEY (`seccion_idseccion`)
    REFERENCES `siga`.`seccion` (`idseccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_asesor1`
    FOREIGN KEY (`asesor_noPersonalAsesor`)
    REFERENCES `siga`.`asesor` (`noPersonalAsesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`grupoAlumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`grupoAlumno` (
  `idGrupoAlumno` INT NOT NULL AUTO_INCREMENT,
  `noAlumnosRegistrados` INT(5) NOT NULL,
  `periodo` VARCHAR(45) NOT NULL,
  `seccion` VARCHAR(45) NOT NULL,
  `curso_idCurso` INT NOT NULL,
  PRIMARY KEY (`idGrupoAlumno`),
  INDEX `fk_grupoAlumno_curso1_idx` (`curso_idCurso` ASC),
  CONSTRAINT `fk_grupoAlumno_curso1`
    FOREIGN KEY (`curso_idCurso`)
    REFERENCES `siga`.`curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`coordinador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`coordinador` (
  `noPersonalCoordinador` INT NOT NULL AUTO_INCREMENT,
  `nombreCoordinador` VARCHAR(45) NOT NULL,
  `apPaternoCoordinador` VARCHAR(45) NOT NULL,
  `apMaternoCoordinador` VARCHAR(45) NULL,
  `correoECoordinador` VARCHAR(45) NOT NULL,
  `telefonoCoordinador` INT(15) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `horarioAtencion_idhorarioAtencion` INT NOT NULL,
  PRIMARY KEY (`noPersonalCoordinador`),
  INDEX `fk_coordinador_usuario1_idx` (`usuario_idusuario` ASC),
  INDEX `fk_coordinador_horarioAtencion1_idx` (`horarioAtencion_idhorarioAtencion` ASC),
  CONSTRAINT `fk_coordinador_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `siga`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coordinador_horarioAtencion1`
    FOREIGN KEY (`horarioAtencion_idhorarioAtencion`)
    REFERENCES `siga`.`horarioAtencion` (`idhorarioAtencion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`calendarioActividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`calendarioActividades` (
  `idCalendarioActividades` INT NOT NULL AUTO_INCREMENT,
  `fechaLimiteExamen` DATE NOT NULL,
  `seccionCalendarioActividades` INT(5) NOT NULL,
  `materialReportar` VARCHAR(45) NOT NULL,
  `moduloCalendarioActividades` INT(2) NOT NULL,
  `convCalendarioActividades` VARCHAR(45) NOT NULL,
  `Coordinador_noPersonalCoordinador` INT NOT NULL,
  PRIMARY KEY (`idCalendarioActividades`),
  INDEX `fk_CalendarioActividades_Coordinador1_idx` (`Coordinador_noPersonalCoordinador` ASC),
  CONSTRAINT `fk_CalendarioActividades_Coordinador1`
    FOREIGN KEY (`Coordinador_noPersonalCoordinador`)
    REFERENCES `siga`.`coordinador` (`noPersonalCoordinador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`inscripcion` (
  `GrupoAlumno_idGrupoAlumno` INT NOT NULL,
  `Alumno_matriculaAlumno` VARCHAR(9) NOT NULL,
  `fecha_inscripcion` DATE NOT NULL,
  `noVaucher` INT(20) NOT NULL,
  PRIMARY KEY (`GrupoAlumno_idGrupoAlumno`, `Alumno_matriculaAlumno`),
  INDEX `fk_GrupoAlumno_has_Alumno_Alumno1_idx` (`Alumno_matriculaAlumno` ASC),
  INDEX `fk_GrupoAlumno_has_Alumno_GrupoAlumno1_idx` (`GrupoAlumno_idGrupoAlumno` ASC),
  CONSTRAINT `fk_GrupoAlumno_has_Alumno_GrupoAlumno1`
    FOREIGN KEY (`GrupoAlumno_idGrupoAlumno`)
    REFERENCES `siga`.`grupoAlumno` (`idGrupoAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GrupoAlumno_has_Alumno_Alumno1`
    FOREIGN KEY (`Alumno_matriculaAlumno`)
    REFERENCES `siga`.`alumno` (`matriculaAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`portafolioEvidencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`portafolioEvidencias` (
  `idportafolioEvidencias` INT NOT NULL AUTO_INCREMENT,
  `reglamento` VARCHAR(45) NOT NULL,
  `CalendarioActividades_idCalendarioActividades` INT NOT NULL,
  `inscripcion_GrupoAlumno_idGrupoAlumno` INT NOT NULL,
  `inscripcion_Alumno_matriculaAlumno` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idportafolioEvidencias`),
  INDEX `fk_portafolioEvidencias_CalendarioActividades1_idx` (`CalendarioActividades_idCalendarioActividades` ASC),
  INDEX `fk_portafolioEvidencias_inscripcion1_idx` (`inscripcion_GrupoAlumno_idGrupoAlumno` ASC, `inscripcion_Alumno_matriculaAlumno` ASC),
  CONSTRAINT `fk_portafolioEvidencias_CalendarioActividades1`
    FOREIGN KEY (`CalendarioActividades_idCalendarioActividades`)
    REFERENCES `siga`.`calendarioActividades` (`idCalendarioActividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_portafolioEvidencias_inscripcion1`
    FOREIGN KEY (`inscripcion_GrupoAlumno_idGrupoAlumno` , `inscripcion_Alumno_matriculaAlumno`)
    REFERENCES `siga`.`inscripcion` (`GrupoAlumno_idGrupoAlumno` , `Alumno_matriculaAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`bitacora` (
  `idBitacora` INT NOT NULL AUTO_INCREMENT,
  `noBitacora` VARCHAR(45) NOT NULL,
  `tiempoEmpleado` TIME NOT NULL,
  `codigoActividad` VARCHAR(45) NOT NULL,
  `comentarios` VARCHAR(45) NOT NULL,
  `desempenoSeccion` VARCHAR(45) NOT NULL,
  `fechaBitacora` VARCHAR(45) NOT NULL,
  `materialesSugeridos` VARCHAR(45) NOT NULL,
  `observacionesAsesor` VARCHAR(45) NOT NULL,
  `ObservacionesUsuario` VARCHAR(45) NOT NULL,
  `resultadoAutoevaluacion` INT(5) NOT NULL,
  `portafolioEvidencias_idportafolioEvidencias` INT NOT NULL,
  PRIMARY KEY (`idBitacora`),
  INDEX `fk_Bitacora_portafolioEvidencias1_idx` (`portafolioEvidencias_idportafolioEvidencias` ASC),
  CONSTRAINT `fk_Bitacora_portafolioEvidencias1`
    FOREIGN KEY (`portafolioEvidencias_idportafolioEvidencias`)
    REFERENCES `siga`.`portafolioEvidencias` (`idportafolioEvidencias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`seguimientoCurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`seguimientoCurso` (
  `idSeguimientoCurso` INT NOT NULL AUTO_INCREMENT COMMENT '	',
  `noSeguimiento` VARCHAR(45) NOT NULL,
  `descripcionSeguimiento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSeguimientoCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`retroalimentación`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`retroalimentación` (
  `noRetroalimentación` INT NOT NULL AUTO_INCREMENT COMMENT '	',
  `nombreRetroalimentacion` VARCHAR(45) NOT NULL,
  `idiomaRetroalimentacion` VARCHAR(45) NOT NULL,
  `tipoRetroalimentacion` VARCHAR(45) NOT NULL,
  `inscripcion_GrupoAlumno_idGrupoAlumno` INT NOT NULL,
  `inscripcion_Alumno_matriculaAlumno` VARCHAR(9) NOT NULL,
  `seccion_idseccion` INT NOT NULL,
  PRIMARY KEY (`noRetroalimentación`),
  INDEX `fk_retroalimentación_inscripcion1_idx` (`inscripcion_GrupoAlumno_idGrupoAlumno` ASC, `inscripcion_Alumno_matriculaAlumno` ASC),
  INDEX `fk_retroalimentación_seccion1_idx` (`seccion_idseccion` ASC),
  CONSTRAINT `fk_retroalimentación_inscripcion1`
    FOREIGN KEY (`inscripcion_GrupoAlumno_idGrupoAlumno` , `inscripcion_Alumno_matriculaAlumno`)
    REFERENCES `siga`.`inscripcion` (`GrupoAlumno_idGrupoAlumno` , `Alumno_matriculaAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_retroalimentación_seccion1`
    FOREIGN KEY (`seccion_idseccion`)
    REFERENCES `siga`.`seccion` (`idseccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`autoevaluación`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`autoevaluación` (
  `idAutoevaluación` INT NOT NULL AUTO_INCREMENT,
  `nombreElaborador` VARCHAR(45) NOT NULL,
  `nombreMaterial` VARCHAR(45) NOT NULL,
  `habilidadesRequeridas` VARCHAR(45) NOT NULL,
  `fechaElaboracion` DATE NOT NULL,
  `contenidosEvaluados` VARCHAR(45) NOT NULL,
  `codificacion` VARCHAR(45) NOT NULL,
  `objetivo` VARCHAR(45) NOT NULL,
  `sala` VARCHAR(5) NOT NULL,
  `nivel` INT(2) NOT NULL,
  `portafolioEvidencias_idportafolioEvidencias` INT NOT NULL,
  PRIMARY KEY (`idAutoevaluación`),
  INDEX `fk_autoevaluación_portafolioEvidencias1_idx` (`portafolioEvidencias_idportafolioEvidencias` ASC),
  CONSTRAINT `fk_autoevaluación_portafolioEvidencias1`
    FOREIGN KEY (`portafolioEvidencias_idportafolioEvidencias`)
    REFERENCES `siga`.`portafolioEvidencias` (`idportafolioEvidencias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`hojaSeguimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`hojaSeguimiento` (
  `idHojaSeguimiento` INT NOT NULL AUTO_INCREMENT,
  `horasEmpleadas` VARCHAR(45) NOT NULL,
  `fechaInicioSesion` VARCHAR(45) NOT NULL,
  `fechaTerminoSesion` VARCHAR(45) NOT NULL,
  `evaluacion` VARCHAR(45) NOT NULL,
  `codificacionMateriales` VARCHAR(45) NOT NULL,
  `analisis` VARCHAR(45) NOT NULL,
  `idioma` VARCHAR(45) NOT NULL,
  `materialSeguimiento` VARCHAR(45) NOT NULL,
  `modulo` VARCHAR(45) NOT NULL,
  `nivel` VARCHAR(45) NOT NULL,
  `objetivo` VARCHAR(45) NOT NULL,
  `seccion` VARCHAR(45) NOT NULL,
  `trabajadorEspSeccion` VARCHAR(45) NOT NULL,
  `trabajadorIntroSeccion` VARCHAR(45) NOT NULL,
  `portafolioEvidencias_idportafolioEvidencias` INT NOT NULL,
  `Asesor_noPersonalAsesor` INT NOT NULL,
  PRIMARY KEY (`idHojaSeguimiento`),
  INDEX `fk_HojaSeguimiento_portafolioEvidencias1_idx` (`portafolioEvidencias_idportafolioEvidencias` ASC),
  INDEX `fk_HojaSeguimiento_Asesor1_idx` (`Asesor_noPersonalAsesor` ASC),
  CONSTRAINT `fk_HojaSeguimiento_portafolioEvidencias1`
    FOREIGN KEY (`portafolioEvidencias_idportafolioEvidencias`)
    REFERENCES `siga`.`portafolioEvidencias` (`idportafolioEvidencias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HojaSeguimiento_Asesor1`
    FOREIGN KEY (`Asesor_noPersonalAsesor`)
    REFERENCES `siga`.`asesor` (`noPersonalAsesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`actividad` (
  `idActividad` INT NOT NULL AUTO_INCREMENT,
  `nombreActividad` VARCHAR(45) NOT NULL,
  `profesorActividad` VARCHAR(45) NOT NULL,
  `tipoActividad` VARCHAR(45) NOT NULL,
  `horaActividad` TIME NOT NULL,
  `diaActividad` DATE NOT NULL,
  PRIMARY KEY (`idActividad`))
ENGINE = InnoDB
COMMENT = 'tipoAsesoria';


-- -----------------------------------------------------
-- Table `siga`.`reservacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`reservacion` (
  `idreservacion` INT NOT NULL AUTO_INCREMENT,
  `fechaReservacion` DATE NOT NULL,
  `fechaRegistro` DATE NOT NULL,
  `CalendarioActividades_idCalendarioActividades` INT NOT NULL,
  `actividad_idActividad` INT NOT NULL,
  `alumno_matriculaAlumno` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idreservacion`),
  INDEX `fk_reservacion_CalendarioActividades1_idx` (`CalendarioActividades_idCalendarioActividades` ASC),
  INDEX `fk_reservacion_actividad1_idx` (`actividad_idActividad` ASC),
  INDEX `fk_reservacion_alumno1_idx` (`alumno_matriculaAlumno` ASC),
  CONSTRAINT `fk_reservacion_CalendarioActividades1`
    FOREIGN KEY (`CalendarioActividades_idCalendarioActividades`)
    REFERENCES `siga`.`calendarioActividades` (`idCalendarioActividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservacion_actividad1`
    FOREIGN KEY (`actividad_idActividad`)
    REFERENCES `siga`.`actividad` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservacion_alumno1`
    FOREIGN KEY (`alumno_matriculaAlumno`)
    REFERENCES `siga`.`alumno` (`matriculaAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`conversacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`conversacion` (
  `noconversacion` INT NOT NULL AUTO_INCREMENT,
  `asesoria_idActividad` INT NOT NULL,
  PRIMARY KEY (`noconversacion`, `asesoria_idActividad`),
  INDEX `fk_conversacion_asesoria1_idx` (`asesoria_idActividad` ASC),
  CONSTRAINT `fk_conversacion_asesoria1`
    FOREIGN KEY (`asesoria_idActividad`)
    REFERENCES `siga`.`actividad` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`asesoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`asesoria` (
  `noAsesoria` INT NOT NULL AUTO_INCREMENT,
  `asesoria_idActividad` INT NOT NULL,
  PRIMARY KEY (`noAsesoria`, `asesoria_idActividad`),
  INDEX `fk_asesoria_asesoria1_idx` (`asesoria_idActividad` ASC),
  CONSTRAINT `fk_asesoria_asesoria1`
    FOREIGN KEY (`asesoria_idActividad`)
    REFERENCES `siga`.`actividad` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`tallerLectura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`tallerLectura` (
  `noTallerLectura` INT NOT NULL AUTO_INCREMENT,
  `asesoria_idActividad` INT NOT NULL,
  PRIMARY KEY (`noTallerLectura`, `asesoria_idActividad`),
  INDEX `fk_tallerLectura_asesoria1_idx` (`asesoria_idActividad` ASC),
  CONSTRAINT `fk_tallerLectura_asesoria1`
    FOREIGN KEY (`asesoria_idActividad`)
    REFERENCES `siga`.`actividad` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`seguimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`seguimiento` (
  `SeguimientoCurso_idSeguimientoCurso` INT NOT NULL,
  `curso_idCurso` INT NOT NULL,
  PRIMARY KEY (`SeguimientoCurso_idSeguimientoCurso`, `curso_idCurso`),
  INDEX `fk_SeguimientoCurso_has_curso1_curso1_idx` (`curso_idCurso` ASC),
  INDEX `fk_SeguimientoCurso_has_curso1_SeguimientoCurso1_idx` (`SeguimientoCurso_idSeguimientoCurso` ASC),
  CONSTRAINT `fk_SeguimientoCurso_has_curso1_SeguimientoCurso1`
    FOREIGN KEY (`SeguimientoCurso_idSeguimientoCurso`)
    REFERENCES `siga`.`seguimientoCurso` (`idSeguimientoCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SeguimientoCurso_has_curso1_curso1`
    FOREIGN KEY (`curso_idCurso`)
    REFERENCES `siga`.`curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`alumnoTieneHistorialObservaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`alumnoTieneHistorialObservaciones` (
  `HistorialObservaciones_idHistorialObservaciones` INT NOT NULL,
  `Alumno_matriculaAlumno` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`HistorialObservaciones_idHistorialObservaciones`, `Alumno_matriculaAlumno`),
  INDEX `fk_HistorialObservaciones_has_Alumno_Alumno1_idx` (`Alumno_matriculaAlumno` ASC),
  INDEX `fk_HistorialObservaciones_has_Alumno_HistorialObservaciones_idx` (`HistorialObservaciones_idHistorialObservaciones` ASC),
  CONSTRAINT `fk_HistorialObservaciones_has_Alumno_HistorialObservaciones1`
    FOREIGN KEY (`HistorialObservaciones_idHistorialObservaciones`)
    REFERENCES `siga`.`historialObservaciones` (`idHistorialObservaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HistorialObservaciones_has_Alumno_Alumno1`
    FOREIGN KEY (`Alumno_matriculaAlumno`)
    REFERENCES `siga`.`alumno` (`matriculaAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`periodoVacacional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`periodoVacacional` (
  `idperiodoVacacional` INT NOT NULL AUTO_INCREMENT,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  `calendarioActividades_idCalendarioActividades` INT NOT NULL,
  PRIMARY KEY (`idperiodoVacacional`, `calendarioActividades_idCalendarioActividades`),
  INDEX `fk_periodoVacacional_calendarioActividades1_idx` (`calendarioActividades_idCalendarioActividades` ASC),
  CONSTRAINT `fk_periodoVacacional_calendarioActividades1`
    FOREIGN KEY (`calendarioActividades_idCalendarioActividades`)
    REFERENCES `siga`.`calendarioActividades` (`idCalendarioActividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`mesCalendario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`mesCalendario` (
  `idmesCalendario` INT NOT NULL AUTO_INCREMENT,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  `calendarioActividades_idCalendarioActividades` INT NOT NULL,
  PRIMARY KEY (`idmesCalendario`, `calendarioActividades_idCalendarioActividades`),
  INDEX `fk_mesCalendario_calendarioActividades1_idx` (`calendarioActividades_idCalendarioActividades` ASC),
  CONSTRAINT `fk_mesCalendario_calendarioActividades1`
    FOREIGN KEY (`calendarioActividades_idCalendarioActividades`)
    REFERENCES `siga`.`calendarioActividades` (`idCalendarioActividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`diasFestivosCalendario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siga`.`diasFestivosCalendario` (
  `iddiasFestivosCalendario` INT NOT NULL AUTO_INCREMENT,
  `diaFestivo` DATE NOT NULL,
  `motivoFestivo` VARCHAR(45) NOT NULL,
  `calendarioActividades_idCalendarioActividades` INT NOT NULL,
  PRIMARY KEY (`iddiasFestivosCalendario`, `calendarioActividades_idCalendarioActividades`),
  INDEX `fk_diasFestivosCalendario_calendarioActividades1_idx` (`calendarioActividades_idCalendarioActividades` ASC),
  CONSTRAINT `fk_diasFestivosCalendario_calendarioActividades1`
    FOREIGN KEY (`calendarioActividades_idCalendarioActividades`)
    REFERENCES `siga`.`calendarioActividades` (`idCalendarioActividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
